logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.pay: DEBUG
    com.github.binarywang.wxpay: DEBUG

wechat:
  pay:
    appId: 
    mchId: 
    mchKey: 
    #subAppId:
    #subMchId:
    keyPath: classpath:apiclient_cert.p12
  miniapp:
    appid: wxf134e694dfd9306a
    secret:
    token: 111
    aesKey: 111
    msgDataFormat:

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_warehouse?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5


server:
  port: 81
  tomcat:
    max-threads: 900
    uri-encoding: utf-8


mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*.xml

swagger:
  enabled: true
  title: swagger
  description: skyisbule.github.com
  version: 1.0
  base-package: com.github.skyisbule.wxpay.controller
  base-path: /**
  exclude-path: /error,/ops/**
  apply-default-response-messages: false
  global-response-message:
    get[1]:
      code: 500
      message: server error
      modelRef: error
    post:
      code : 500
      message: server error
      modelRef: error

qiniu:
  accessKey: dcNxos-8d9hb222GRRyI5dWlsMI0hARssZA_Bspn
  secretKey:
  bucket: warehouse